server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/social_photo
    username: root
    password: mydatabase
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: PhotoService

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: true
    show-sql: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

photo:
  filePath: /Users/macbookpro/Documents/University/Internship/Social Media/photo/src/main/resources/images
